databases:
  - name: btpdb
    plan: free
    databaseName: btp
    user: btppguser

services:
  - type: web
    plan: free
    name: btp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn btp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: btpdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4