# Generated by Django 5.0.4 on 2024-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0003_mymodel_q10_mymodel_q11_mymodel_q12_mymodel_q13_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.IntegerField()),
                ("q2", models.IntegerField()),
                ("q3", models.IntegerField()),
                ("q4", models.IntegerField()),
                ("q5", models.IntegerField()),
                ("q6", models.IntegerField()),
                ("q7", models.IntegerField()),
                ("q8", models.IntegerField()),
                ("q9", models.IntegerField()),
                ("q10", models.IntegerField()),
                ("q11", models.IntegerField()),
                ("q12", models.IntegerField()),
                ("q13", models.IntegerField()),
                ("q14", models.IntegerField()),
                ("q15", models.IntegerField()),
                ("q16", models.IntegerField()),
                ("q17", models.IntegerField()),
                ("q18", models.IntegerField()),
                ("q19", models.IntegerField()),
                ("q20", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
